name: orange_wallet_core
version: 0.0.1
author: "BaojunCZ<baojun.cz@gmail.com>"
homepage: https://github.com/OrangeWallet/bip44.git
description: It is core of Orange Wallet(https://github.com/OrangeWallet/orange-wallet)
publish_to: https://pub.dartlang.org/

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  bip32: ^1.0.5
  ckb_sdk:
    git:
      url: https://github.com/BaojunCZ/ckb-sdk-dart.git

dev_dependencies:
  test: ^1.6.1
