name: ckbcore
version: 0.14.0
author: "BaoJunCZ<baojun.cz@gmail.com>"
homepage: https://github.com/OrangeWallet/ckbcore
description: It is core of Orange Wallet(https://github.com/OrangeWallet/orange-wallet)
publish_to: https://pub.dartlang.org/

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  uuid: ^2.0.1
  ckb_sdk:
    git:
      url: https://github.com/BaojunCZ/ckb-sdk-dart.git
      ref: v0.15.0

dev_dependencies:
  test: ^1.6.1
